services:
  pn9w4q7x2m:
    container_name: pn9w4q7x2m_app
    image: ghcr.io/mr-devloper005/prnowe.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3069:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
